name: build

on:
  push:
    paths-ignore:
      - "tutorial.ipynb"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "tutorial.ipynb"
      - "docs/**"

jobs:
  run-robopianist-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["python:3.11"]
    steps:
      - name: Checkout robopianist
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        shell: bash
        run: |
          bash scripts/install_deps.sh
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e ".[test]"
      - name: Run tests
        run: |
          make test
